config/routes.rb
Rails.application.routes.draw do
    root 'pages#dashboard'
    get 'dashboard' => 'pages#dashboard'
    devise_for :users, :controllers => { :registrations => "users" }
    devise_for :taxpayers, :controllers => { :registrations => "taxpayers"}

    resources :users, except: [:destroy]

    resources :taxpayers do
      match :delinquent, via: [:get], on: :collection
       match :with_pending_payments, via: [:get], on: :collection
      resources :businesses
      resources :cedulas
    end
    resources :businesses, except: [:destroy] do
      match :renew, via: [:get], on: :member
      match :registered, via: [:get], on: :collection
      match :delinquent, via: [:get], on: :collection
      match :payment_pending, via: [:get], on: :collection
      match :new_business, via: [:get], on: :collection
      match :owned_by_women, via: [:get], on: :collection
      match :expire, via: [:get, :post], on: :member
      match :retire, via: [:get, :post], on: :member
      match :revoke, via: [:get, :post], on: :member
      match :revoked, via: :get, on: :collection
      resources :payments, only: [:new, :create]
      resources :line_of_businesses
    end
          resources :payments,  only: [:index]
          resources :line_of_businesses

      get 'reports' => 'reports#index', as: 'reports'
      get 'quarterly_reports' => 'reports#quarterly', as: 'quarterly_reports'
      get 'delinquents_ahin' => 'businesses#delinquents_ahin'
      get 'delinquents_apapid' => 'businesses#delinquents_apapid'
      get 'delinquents_binablayan' => 'businesses#delinquents_binablayan'
      get 'delinquents_danggo' => 'businesses#delinquents_danggo'
      get 'delinquents_eheb' => 'businesses#delinquents_eheb'
      get 'delinquents_gumhang' => 'businesses#delinquents_gumhang'
      get 'delinquents_impugong' => 'businesses#delinquents_impugong'
      get 'delinquents_luhong' => 'businesses#delinquents_luhong'
      get 'delinquents_poblacion' => 'businesses#delinquents_poblacion'
      get 'delinquents_tukucan' => 'businesses#delinquents_tukucan'
      get 'delinquents_tulludan' => 'businesses#delinquents_tulludan'
      get 'delinquents_wangwang' => 'businesses#delinquents_wangwang'

      get 'registered_ahin' => 'businesses#registered_ahin'
      get 'registered_apapid' => 'businesses#registered_apapid'
      get 'registered_binablayan' => 'businesses#registered_binablayan'
      get 'registered_danggo' => 'businesses#registered_danggo'
      get 'registered_eheb' => 'businesses#registered_eheb'
      get 'registered_gumhang' => 'businesses#registered_gumhang'
      get 'registered_impugong' => 'businesses#registered_impugong'
      get 'registered_luhong' => 'businesses#registered_luhong'
      get 'registered_poblacion' => 'businesses#registered_poblacion'
      get 'registered_tukucan' => 'businesses#registered_tukucan'
      get 'registered_tulludan' => 'businesses#registered_tulludan'
      get 'registered_wangwang' => 'businesses#registered_wangwang'

      get 'dole_report' => 'businesses#dole_report'
      get 'sss_report' => 'businesses#sss_report'
      get 'registered_businesses_report' => 'businesses#registered_businesses_report'
      get 'new_businesses_report' => 'businesses#new_businesses_report'
      get 'unrenewed_businesses_report' => 'businesses#unrenewed_businesses_report'
      get 'bir_report' => 'businesses#bir_report'
  end

app/models/concerns/business/enterprise_scale_setter.rb
module Business::EnterpriseScaleSetter
    def micro_industry?
      self.asset_size<=150_000
    end

    def cottage_industry?
      self.asset_size<=1_500_000
    end

    def small_scale_industry?
      self.asset_size<=15_000_000
    end

    def medium_industry?
      self.asset_size<=60_000_000
    end

    def large_industry?
      self.asset_size>60_000_001
    end

    private
    def set_enterprise_scale
      return self.enterprise_scale=:micro if self.micro_industry?
      return self.enterprise_scale=:cottage if self.cottage_industry?
      return self.enterprise_scale=:small_scale if self.small_scale_industry?
      return self.enterprise_scale=:medium if self.medium_industry?
      return self.enterprise_scale=:large if self.large_industry?
    end
  end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_filter :set_business, only: [:edit, :show, :update]

  def registered
    if params[:query].present?
      @businesses = Business.include[:taxpayer, :line_of_businesses].text_search(params[:query]).page(params[:page]).per_page(50)
    else
      @businesses = Business.page(params[:page]).per_page(50)
    end
  end
  def delinquent
    if params[:query].present?
      @businesses = Business.delinquent.text_search(params[:query]).page(params[:page]).per_page(50)
    else
      @businesses = Business.delinquent.page(params[:page]).per_page(50)
    end
  end


  def delinquents_poblacion
    @businesses = Business.delinquent.where(address_barangay: 'Poblacion')
     respond_to do |format|
     format.html
      format.pdf do
        pdf = DelinquencyReportPdf.new(@businesses)
        send_data pdf.render, filename: "permit.pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end
    def registered_poblacion
    @businesses = Business.registered.where(address_barangay: 'Poblacion').order(:permit_number)
     respond_to do |format|
     format.html
      format.pdf do
        pdf = RegisteredBusinessesPerBarangayReportPdf.new(@businesses)
        send_data pdf.render, filename: "registered(Poblacion).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end
  def delinquents_impugong
    @businesses = Business.delinquent.where(address_barangay: 'Impugong')
     respond_to do |format|
     format.html
      format.pdf do
        pdf = RegisteredBusinessesPerBarangayReportPdf.new(@businesses)
        send_data pdf.render, filename: "delinquent(Impugong).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def registered_impugong
    @businesses = Business.registered.where(address_barangay: 'Impugong').order(:permit_number)
     respond_to do |format|
     format.html
      format.pdf do
        pdf = RegisteredBusinessesPerBarangayReportPdf.new(@businesses)
        send_data pdf.render, filename: "registered(Impugong).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def delinquents_ahin
    @businesses = Business.delinquent.where(address_barangay: 'Ahin')
     respond_to do |format|
     format.html
      format.pdf do
        pdf = DelinquencyReportPdf.new(@businesses)
        send_data pdf.render, filename: "delinquent(Ahin).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def registered_ahin
    @businesses = Business.registered.where(address_barangay: 'Ahin').order(:permit_number)
     respond_to do |format|
     format.html
      format.pdf do
        pdf = RegisteredBusinessesPerBarangayReportPdf.new(@businesses)
        send_data pdf.render, filename: "registered(Ahin).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def delinquents_apapid
    @businesses = Business.delinquent.where(address_barangay: 'Ap-apid')
     respond_to do |format|
     format.html
      format.pdf do
        pdf = DelinquencyReportPdf.new(@businesses)
        send_data pdf.render, filename: "delinquent(Ap-apid).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

   def registered_apapid
    @businesses = Business.registered.where(address_barangay: 'Ap-apid').order(:permit_number)
     respond_to do |format|
     format.html
      format.pdf do
        pdf = RegisteredBusinessesPerBarangayReportPdf.new(@businesses)
        send_data pdf.render, filename: "registered(Ap-apid).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def delinquents_binablayan
    @businesses = Business.delinquent.where(address_barangay: 'Binablayan')
     respond_to do |format|
     format.html
      format.pdf do
        pdf = DelinquencyReportPdf.new(@businesses)
        send_data pdf.render, filename: "delinquent(Binablayan).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

   def registered_binablayan
    @businesses = Business.registered.where(address_barangay: 'Binablayan').order(:permit_number)
     respond_to do |format|
     format.html
      format.pdf do
        pdf = RegisteredBusinessesPerBarangayReportPdf.new(@businesses)
        send_data pdf.render, filename: "registered(Binablayan).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def delinquents_wangwang
    @businesses = Business.delinquent.where(address_barangay: 'Wangwang')
     respond_to do |format|
     format.html
      format.pdf do
        pdf = DelinquencyReportPdf.new(@businesses)
        send_data pdf.render, filename: "delinquent(Wangwang).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def registered_wangwang
    @businesses = Business.registered.where(address_barangay: 'Wangwang').order(:permit_number)
     respond_to do |format|
     format.html
      format.pdf do
        pdf = RegisteredBusinessesPerBarangayReportPdf.new(@businesses)
        send_data pdf.render, filename: "registered(Wangwang).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def delinquents_eheb
    @businesses = Business.delinquent.where(address_barangay: 'Eheb')
     respond_to do |format|
     format.html
      format.pdf do
        pdf = DelinquencyReportPdf.new(@businesses)
        send_data pdf.render, filename: "delinquent(Eheb).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def registered_eheb
    @businesses = Business.registered.where(address_barangay: 'Eheb').order(:permit_number)
     respond_to do |format|
     format.html
      format.pdf do
        pdf = RegisteredBusinessesPerBarangayReportPdf.new(@businesses)
        send_data pdf.render, filename: "registered(Eheb).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def delinquents_danggo
    @businesses = Business.delinquent.where(address_barangay: 'Danggo')
     respond_to do |format|
     format.html
      format.pdf do
        pdf = DelinquencyReportPdf.new(@businesses)
        send_data pdf.render, filename: "delinquent(Danggo).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def registered_danggo
    @businesses = Business.registered.where(address_barangay: 'Danggo').order(:permit_number)
     respond_to do |format|
     format.html
      format.pdf do
        pdf = RegisteredBusinessesPerBarangayReportPdf.new(@businesses)
        send_data pdf.render, filename: "registered(Danggo).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def delinquents_luhong
    @businesses = Business.delinquent.where(address_barangay: 'Luhong')
     respond_to do |format|
      format.pdf do
        pdf = DelinquencyReportPdf.new(@businesses)
        send_data pdf.render, filename: "delinquent(Luhong).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

   def registered_luhong
    @businesses = Business.registered.where(address_barangay: 'Luhong').order(:permit_number)
     respond_to do |format|
      format.pdf do
        pdf = RegisteredBusinessesPerBarangayReportPdf.new(@businesses)
        send_data pdf.render, filename: "registered(Luhong).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def delinquents_gumhang
    @businesses = Business.delinquent.where(address_barangay: 'Gumhang')
     respond_to do |format|
      format.pdf do
        pdf = DelinquencyReportPdf.new(@businesses)
        send_data pdf.render, filename: "delinquent(Gumhang).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def registered_gumhang
    @businesses = Business.registered.where(address_barangay: 'Gumhang').order(:permit_number)
     respond_to do |format|
      format.pdf do
        pdf = RegisteredBusinessesPerBarangayReportPdf.new(@businesses)
        send_data pdf.render, filename: "registered(Gumhang).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end


  def delinquents_tulludan
    @businesses = Business.delinquent.where(address_barangay: 'Tulludan')
     respond_to do |format|
     format.html
      format.pdf do
        pdf = DelinquencyReportPdf.new(@businesses)
        send_data pdf.render, filename: "delinquent(Tulludan).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def registered_tulludan
    @businesses = Business.registered.where(address_barangay: 'Tulludan').order(:permit_number)
     respond_to do |format|
     format.html
      format.pdf do
        pdf = RegisteredBusinessesPerBarangayReportPdf.new(@businesses)
        send_data pdf.render, filename: "registered(Tulludan).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end


  def delinquents_tukucan
    @businesses = Business.delinquent.where(address_barangay: 'Tukucan')
     respond_to do |format|
     format.html
      format.pdf do
        pdf = DelinquencyReportPdf.new(@businesses)
        send_data pdf.render, filename: "delinquent(Tukucan).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

   def registered_tukucan
    @businesses = Business.registered.where(address_barangay: 'Tukucan').order(:permit_number)
     respond_to do |format|
     format.html
      format.pdf do
        pdf = RegisteredBusinessesPerBarangayReportPdf.new(@businesses)
        send_data pdf.render, filename: "registered(Tukucan).pdf", type: 'application/pdf', disposition: "inline"
      end
    end
  end

  def index
    if params[:query].present?
    @businesses = Business.text_search(params[:query]).page(params[:page]).per_page(30)
  else
    @businesses = Business.order('created_at asc').page(params[:page]).per_page(30)
    end
  end
  def dole_report
    @businesses = Business.registered
    @taxpayers = Taxpayer.all
    respond_to do |format|
      format.html
      format.pdf do

app/views/businesses/_index.html.erb
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
         <div class="panel panel-default">
                <div class="panel-body">
                <h4>List of Businesses
                  <div class="pull-right">

                    <%=form_tag businesses_path, method: :get do %>
      <div class="input-group">
        <%=text_field_tag :query, params[:query], class: 'form-control', placeholder: 'Search...' %>
        <span class="input-group-btn">
          <%= button_tag(type: 'submit', class: "btn btn-default btn-flat") do %>
            <i class="fa fa-search"></i>
            <% end %>
               </span>
      </div>
      <% end %>
      </div>
    </h4>
    <hr />



            <div class="table-responsive">
              <table class="table table-hover no-margin">
                <thead>
                  <tr>
                    <th><b>BUSINESS NAME </b></th>
                    <th><b> OWNER </b></th>
                    <th><b> STATUS </b></th>
                  </tr>
                </thead>
                <tbody>
                  <% @businesses.each do |business| %>
                    <tr>
                      <td><b><%=link_to truncate(business.business_name.upcase, length: 40), business%></b></td>
                      <td><%= business.taxpayer_full_name %></td>
                      <td class="label label-<%='success' if business.registered? %>"><%=business.status.to_s.titleize%></td>
                      <td>
                      <% if business.payment_pending?  %>
                       <%=link_to 'Pay', new_business_payment_path(business)%>
                       <% end %>
                         <% if business.expired? %>
                       <%=link_to 'Renew', renew_business_path(business), method: :get%>
                       <% end %>

                        <% if business.delinquent? %>
                       <%=link_to 'Pay Dues', renew_business_path(business), method: :get %>
                       <% end %>
                       <% if business.registered? && current_user.system_administrator? && business.line_of_businesses.present?%>
                       <%=link_to ' Print Mayors Permit', business_path(business, format: "pdf"), class: " btn  fa fa-print" %>
                       <% end %>


                      </td>
                    </tr>
                  <%end%>
                </tbody>
              </table>
              <div class="pagination">
            <%= will_paginate @businesses %>
              </div>
            </div>
           </div>
        </div>
      </div>
    </div>

app/views/businesses/delinquent.html.erb
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
         <div class="box box-success">
                <div class="box-header with-border">
                <h3 class="box-title">All Businesses</h3>
                  <div class="box-tools pull-right">

                    <%=form_tag businesses_path, method: :get do %>
      <div class="input-group">
        <%=text_field_tag :query, params[:query], class: 'form-control', placeholder: 'Search...' %>
        <span class="input-group-btn">
          <%= button_tag(type: 'submit', class: "btn btn-flat") do %>
            <i class="fa fa-search"></i>
            <% end %>
               </span>
      </div>
      <% end %>
      </div>

                  </div>
                   <div class="box-body no-padding">
            <div class="table-responsive">
              <table class="table table-hover table-condensed">
                <thead>
                  <tr>
                    <th> Business Name</th>
                    <th>Owner</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <% @businesses.each do |business| %>
                    <tr>
                      <td><%=link_to truncate(business.business_name.upcase, length: 40), business, class: 'text-danger'%></td>
                      <td><%= link_to business.taxpayer_name, taxpayer_path(id: business.taxpayer.id) %></td>
                      <td><%=business.status%></td>
                      <td>
                      <% if business.payment_pending?  %>
                       <%=link_to 'Pay', new_business_payment_path(business)%>
                       <% end %>
                         <% if business.expired? %>
                       <%=link_to 'Renew', renew_business_path(business), method: :get%>
                       <% end %>

                        <% if business.delinquent? %>
                       <%=link_to 'Pay Dues', renew_business_path(business), method: :get %>
                       <% end %>
                       <% if business.registered? && current_user.system_administrator? && business.line_of_businesses.present?%>
                       <%=link_to ' Print Mayors Permit', business_path(business, format: "pdf"), class: " btn  fa fa-print" %>
                       <% end %>


                      </td>
                    </tr>
                  <%end%>
                </tbody>
              </table>
              <div class="pagination">
            <%= will_paginate @businesses %>
              </div>
            </div>
           </div>
        </div>
      </div>
    </div>

app/views/businesses/edit.html.erb
<%provide(:title, "Edit | #{@business.business_name}") %>
<%=render 'form' %>

app/views/businesses/index.html.erb
<%=render 'index' %>

app/views/businesses/new_business.html.erb
<%provide(:title, "New Businesses") %>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
         <div class="box box-info">
                <div class="box-header with-border">
                <h3 class="box-title">New Businesses</h3>
                  <div class="box-tools pull-right">
                    <span class="label label-ino"><%=@businesses.new_business.count %></span>
                  </div>




                   <div class="box-body no-padding">
            <div class="table-responsive">
              <table class="table table-hover table-condensed">
                <thead>
                  <tr>
                    <th> Business Name</th>
                    <th>Owner</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <% @businesses.new_business.each do |business| %>
                    <tr>
                      <td><%=link_to truncate(business.business_name.upcase, length: 40), business %></td>
                      <td><%= link_to business.taxpayer_name, taxpayer_path(id: business.taxpayer.id) %></td>
                      <td><%=business.status%></td>
                    </tr>
                  <%end%>
                </tbody>
              </table>
              <div class="pagination">
            <%= will_paginate @businesses %>
              </div>
            </div>
           </div>
        </div>
      </div>
    </div>

app/views/businesses/owned_by_women.html.erb
<%provide(:title, "Businesses Owned By Women") %>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
         <div class="box box-info">
                <div class="box-header with-border">
                <h3 class="box-title">Businesses Owned By Women</h3>
                  <div class="box-tools pull-right">
                    <span class="label label-info"><%=@businesses.owned_by_women.count %></span>
                  </div>




                   <div class="box-body no-padding">
            <div class="table-responsive">
              <table class="table table-hover table-condensed">
                <thead>
                  <tr>
                    <th> Business Name</th>
                    <th>Owner</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <% @businesses.each do |business| %>
                    <tr>
                      <td><%=link_to truncate(business.business_name.upcase, length: 40), business %></td>
                      <td><%= link_to business.taxpayer_name, taxpayer_path(id: business.taxpayer.id) %></td>
                      <td><%=business.status%></td>
                    </tr>
                  <%end%>
                </tbody>
              </table>
              <div class="pagination">
            <%= will_paginate @businesses %>
              </div>
            </div>
           </div>
        </div>
      </div>
    </div>

app/views/businesses/payment_pending.html.erb
<%provide(:title, "Businesses With Pending Payments") %>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
         <div class="box box-warning">
                <div class="box-header with-border">
                <h3 class="box-title">Businesses With Pending Payments</h3>
                  <div class="box-tools pull-right">
                    <span class="label label-warning"><%=@businesses.payment_pending.count %></span>
                  </div>




                   <div class="box-body no-padding">
            <div class="table-responsive">
              <table class="table table-hover table-condensed">
                <thead>
                  <tr>
                    <th> Business Name</th>
                    <th>Owner</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <% @businesses.each do |business| %>
                    <tr>
                      <td><%=link_to truncate(business.business_name.upcase, length: 40), business %></td>
                      <td><%= link_to business.taxpayer_name, taxpayer_path(id: business.taxpayer.id) %></td>
                      <td><%=business.status%></td>
                    </tr>
                  <%end%>
                </tbody>
              </table>
              <div class="pagination">
            <%= will_paginate @businesses %>
              </div>
            </div>
           </div>
        </div>
      </div>
    </div>

app/views/businesses/registered.html.erb
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
         <div class="panel panel-default panel-with-shadow">
            <div class="panel-heading">

                <h4>Registered Businesses</h4>

                 </div>
                   <div class="panel-body">
            <div class="table-responsive">
              <table class="table table-hover table-condensed">
                <thead>
                  <tr>
                    <th> Business Name</th>
                    <th>Owner</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <% @businesses.registered.each do |business| %>
                    <tr>
                      <td><%=link_to truncate(business.business_name.upcase, length: 40), business%></td>
                      <td><%= link_to business.taxpayer_name, taxpayer_path(id: business.taxpayer.id) %></td>
                      <td><%=business.status%></td>
                      <td>
                      <% if business.payment_pending?  %>
                       <%=link_to 'Pay', new_business_payment_path(business)%>
                       <% end %>
                         <% if business.expired? %>
                       <%=link_to 'Renew', renew_business_path(business), method: :get%>
                       <% end %>

                        <% if business.delinquent? %>
                       <%=link_to 'Pay Dues', renew_business_path(business), method: :get %>
                       <% end %>
                       <% if business.registered? && current_user.system_administrator? && business.line_of_businesses.present?%>
                       <%=link_to ' Print Mayors Permit', business_path(business, format: "pdf"), class: " btn  fa fa-print" %>
                       <% end %>


                      </td>
                    </tr>
                  <%end%>
                </tbody>
              </table>
              <div class="pagination">
            <%= will_paginate @businesses %>
              </div>
            </div>
           </div>
        </div>
      </div>
    </div>

app/views/businesses/renew.html.erb
<%=render 'form' %>

app/views/businesses/revoke.html.erb
<div class="col-md-8 col-md-offset-2">
<div class="box box-danger">
<h4><%=@business.business_name %></h4>
<h5><%=@business.taxpayer_name %></h5>
 <%= simple_form_for @business, html: { class: 'form-horizontal' },
        wrapper: :horizontal_form,
        wrapper_mappings: {
        check_boxes: :horizontal_radio_and_checkboxes,
        radio_buttons: :horizontal_radio_and_checkboxes,
        file: :horizontal_file_input,
        boolean: :horizontal_boolean
        } do |f| %>

          <%=f.error_notification %><%=f.input :reason_of_revocation, label: "State The Reason of Revocation"%>
<div class="modal-footer">
<%=f.submit 'Revoke', class: 'btn btn-danger' %>
  <%= link_to 'or Cancel', :back, class: 'btn btn-link' %>
</div>
<% end %>
</div>
</div>

app/views/businesses/revoked.html.erb
<%provide(:title, "Revoked Business Permits") %>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
         <div class="box box-success">
                <div class="box-header with-border">
                <h3 class="box-title">Revoked Businesses</h3>
                  <div class="box-tools pull-right">
                    <span class="label label-danger"><%=@businesses.revoked.count %></span>
                  </div>




                   <div class="box-body no-padding">
            <div class="table-responsive">
              <table class="table table-hover table-condensed">
                <thead>
                  <tr>
                    <th> Business Name</th>
                    <th>Owner</th>
                    <th>Status</th>
                    <th>Date Revoked</th>
                    <th>Reason of Revocation</th>
                  </tr>
                </thead>
                <tbody>
                  <% @businesses.each do |business| %>
                    <tr>
                      <td><%=link_to truncate(business.business_name.upcase, length: 40), business, class: 'text-danger'%></td>
                      <td><%= link_to business.taxpayer_name, taxpayer_path(id: business.taxpayer.id), class: 'text-danger' %></td>
                      <td><%=business.status%></td>
                      <td><%=business.revoked_at %></td>
                      <td><%=business.reason_of_revocation %></td>
                    </tr>
                  <%end%>
                </tbody>
              </table>
              <div class="pagination">
            <%= will_paginate @businesses %>
              </div>
            </div>
           </div>
        </div>
      </div>
    </div>