config/routes.rb
Rails.application.routes.draw do
    root 'pages#dashboard'
    get 'dashboard' => 'pages#dashboard'
    devise_for :users, :controllers => { :registrations => "users" }
    devise_for :taxpayers, :controllers => { :registrations => "taxpayers"}

    resources :users, except: [:destroy]

    resources :taxpayers do
      match :delinquent, via: [:get], on: :collection
       match :with_pending_payments, via: [:get], on: :collection
      resources :businesses
      resources :cedulas
    end
    resources :businesses, except: [:destroy] do
      match :renew, via: [:get], on: :member
      match :registered, via: [:get], on: :collection
      match :delinquent, via: [:get], on: :collection
      match :payment_pending, via: [:get], on: :collection
      match :new_business, via: [:get], on: :collection
      match :owned_by_women, via: [:get], on: :collection
      match :expire, via: [:get, :post], on: :member
      match :retire, via: [:get, :post], on: :member
      match :revoke, via: [:get, :post], on: :member
      match :revoked, via: :get, on: :collection
      resources :payments, only: [:new, :create]
      resources :line_of_businesses
    end
          resources :payments,  only: [:index]
          resources :line_of_businesses

      get 'reports' => 'reports#index', as: 'reports'
      get 'quarterly_reports' => 'reports#quarterly', as: 'quarterly_reports'
      get 'delinquents_ahin' => 'businesses#delinquents_ahin'
      get 'delinquents_apapid' => 'businesses#delinquents_apapid'
      get 'delinquents_binablayan' => 'businesses#delinquents_binablayan'
      get 'delinquents_danggo' => 'businesses#delinquents_danggo'
      get 'delinquents_eheb' => 'businesses#delinquents_eheb'
      get 'delinquents_gumhang' => 'businesses#delinquents_gumhang'
      get 'delinquents_impugong' => 'businesses#delinquents_impugong'
      get 'delinquents_luhong' => 'businesses#delinquents_luhong'
      get 'delinquents_poblacion' => 'businesses#delinquents_poblacion'
      get 'delinquents_tukucan' => 'businesses#delinquents_tukucan'
      get 'delinquents_tulludan' => 'businesses#delinquents_tulludan'
      get 'delinquents_wangwang' => 'businesses#delinquents_wangwang'

      get 'registered_ahin' => 'businesses#registered_ahin'
      get 'registered_apapid' => 'businesses#registered_apapid'
      get 'registered_binablayan' => 'businesses#registered_binablayan'
      get 'registered_danggo' => 'businesses#registered_danggo'
      get 'registered_eheb' => 'businesses#registered_eheb'
      get 'registered_gumhang' => 'businesses#registered_gumhang'
      get 'registered_impugong' => 'businesses#registered_impugong'
      get 'registered_luhong' => 'businesses#registered_luhong'
      get 'registered_poblacion' => 'businesses#registered_poblacion'
      get 'registered_tukucan' => 'businesses#registered_tukucan'
      get 'registered_tulludan' => 'businesses#registered_tulludan'
      get 'registered_wangwang' => 'businesses#registered_wangwang'

      get 'dole_report' => 'businesses#dole_report'
      get 'sss_report' => 'businesses#sss_report'
      get 'registered_businesses_report' => 'businesses#registered_businesses_report'
      get 'new_businesses_report' => 'businesses#new_businesses_report'
      get 'unrenewed_businesses_report' => 'businesses#unrenewed_businesses_report'
      get 'bir_report' => 'businesses#bir_report'
  end

app/controllers/line_of_businesses_controller.rb
class LineOfBusinessesController < ApplicationController
before_filter :current_business, only: [:new, :create]
  def index
   @line_of_businesses = LineOfBusiness.all
  end

  def new
    @business= current_business
    @line_of_business = current_business.line_of_businesses.build
  end

  def create
    @line_of_business = current_business.line_of_businesses.create(line_of_business_params)
    if @line_of_business.save
      redirect_to @business, notice: 'created successfully'
    else
      render :new
    end
  end

  def edit
    @line_of_business = LineOfBusiness.find(params[:id])
    @business = @line_of_business.business
  end

  def update
    @line_of_business = LineOfBusiness.find(params[:id])
    if @line_of_business.update(line_of_business_params)
      redirect_to business_path(id: @line_of_business.business), notice: "#{@line_of_business.business_name} Line of Business updated successfully."

    else
      render :edit
    end
  end

  private
      def line_of_business_params
        params.require(:line_of_business).permit( :description, :psic_code)
      end

      def current_business
        @business = Business.find(params[:business_id])
      end

end

app/helpers/line_of_businesses_helper.rb
module LineOfBusinessesHelper
end

app/views/line_of_businesses/_form.html.erb
 <div class="col-md-6 col-md-offset-2">
 <div class="box box-success">
  <div class="box-header with-border">
   <h3 class="text-success"><%=@business.business_name.capitalize %> </h3>
   <span class="help-block">Owner: <%=@business.taxpayer_name %></span>
    <span class="help-block">Address: <%=@business.address %></span>


   <hr>
  <%= simple_form_for [@business, @line_of_business], html: { class: 'form-horizontal' },
wrapper: :horizontal_form,
wrapper_mappings: {
check_boxes: :horizontal_radio_and_checkboxes,
radio_buttons: :horizontal_radio_and_checkboxes,
file: :horizontal_file_input,
boolean: :horizontal_boolean
} do |f| %>
<%=f.error_notification %>

              <%=f.input :description %>
              <%=f.input :psic_code  %>

        <div class="modal-footer">
        <% if @line_of_business.new_record? %>
        <%=f.submit 'Add Line Of Business', class: 'btn btn-primary btn-flat' %>
        <% else %>
         <%=f.submit 'Update Line of Business', class: 'btn btn-success btn-flat' %>
        <% end %>
       <%= link_to 'or Cancel', :back, class: 'btn btn-link' %>
    </div>

        <% end %>
  </div>
</div>

app/views/line_of_businesses/index.html.erb
<% provide(:title, 'Line of Businesses') %>
  <div class="well well-sm">
      <%=link_to ' New Line of Business', new_line_of_business_path, class: 'btn btn-primary fa fa-plus', 'data-no-turbolinks' => true%>
    </div>

<div class="panel panel-info">
    <div class='panel-body'>
      <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Description</th>
            <th>Amount</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @line_of_businesses.each do |line_of_business| %>
            <tr>
              <td><%= line_of_business.description %></td>
              <td><%= link_to "Edit |", edit_line_of_business_path(line_of_business),  class: 'fa fa-plus' %>
                  <%=link_to ' Delete', line_of_business_path(line_of_business),
                    :method => :delete,  class: 'fa fa-trash-o',
                    :data   =>{confirm: 'Are you sure you want to delete this line_of_business?'}%>
             </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
  </div>