config/routes.rb
Rails.application.routes.draw do
    root 'pages#dashboard'
    get 'dashboard' => 'pages#dashboard'
    devise_for :users, :controllers => { :registrations => "users" }
    devise_for :taxpayers, :controllers => { :registrations => "taxpayers"}

    resources :users, except: [:destroy]

    resources :taxpayers do
      match :delinquent, via: [:get], on: :collection
       match :with_pending_payments, via: [:get], on: :collection
      resources :businesses
      resources :cedulas
    end
    resources :businesses, except: [:destroy] do
      match :renew, via: [:get], on: :member
      match :registered, via: [:get], on: :collection
      match :delinquent, via: [:get], on: :collection
      match :payment_pending, via: [:get], on: :collection
      match :new_business, via: [:get], on: :collection
      match :owned_by_women, via: [:get], on: :collection
      match :expire, via: [:get, :post], on: :member
      match :retire, via: [:get, :post], on: :member
      match :revoke, via: [:get, :post], on: :member
      match :revoked, via: :get, on: :collection
      resources :payments, only: [:new, :create]
      resources :line_of_businesses
    end
          resources :payments,  only: [:index]
          resources :line_of_businesses

      get 'reports' => 'reports#index', as: 'reports'
      get 'quarterly_reports' => 'reports#quarterly', as: 'quarterly_reports'
      get 'delinquents_ahin' => 'businesses#delinquents_ahin'
      get 'delinquents_apapid' => 'businesses#delinquents_apapid'
      get 'delinquents_binablayan' => 'businesses#delinquents_binablayan'
      get 'delinquents_danggo' => 'businesses#delinquents_danggo'
      get 'delinquents_eheb' => 'businesses#delinquents_eheb'
      get 'delinquents_gumhang' => 'businesses#delinquents_gumhang'
      get 'delinquents_impugong' => 'businesses#delinquents_impugong'
      get 'delinquents_luhong' => 'businesses#delinquents_luhong'
      get 'delinquents_poblacion' => 'businesses#delinquents_poblacion'
      get 'delinquents_tukucan' => 'businesses#delinquents_tukucan'
      get 'delinquents_tulludan' => 'businesses#delinquents_tulludan'
      get 'delinquents_wangwang' => 'businesses#delinquents_wangwang'

      get 'registered_ahin' => 'businesses#registered_ahin'
      get 'registered_apapid' => 'businesses#registered_apapid'
      get 'registered_binablayan' => 'businesses#registered_binablayan'
      get 'registered_danggo' => 'businesses#registered_danggo'
      get 'registered_eheb' => 'businesses#registered_eheb'
      get 'registered_gumhang' => 'businesses#registered_gumhang'
      get 'registered_impugong' => 'businesses#registered_impugong'
      get 'registered_luhong' => 'businesses#registered_luhong'
      get 'registered_poblacion' => 'businesses#registered_poblacion'
      get 'registered_tukucan' => 'businesses#registered_tukucan'
      get 'registered_tulludan' => 'businesses#registered_tulludan'
      get 'registered_wangwang' => 'businesses#registered_wangwang'

      get 'dole_report' => 'businesses#dole_report'
      get 'sss_report' => 'businesses#sss_report'
      get 'registered_businesses_report' => 'businesses#registered_businesses_report'
      get 'new_businesses_report' => 'businesses#new_businesses_report'
      get 'unrenewed_businesses_report' => 'businesses#unrenewed_businesses_report'
      get 'bir_report' => 'businesses#bir_report'
  end

app/models/payment.rb
class Payment < ActiveRecord::Base

   include PgSearch
    pg_search_scope :text_search, against: [:official_receipt_number],
    using: {tsearch: {dictionary: "english", prefix: true}}

    enum status: [:paid, :unpaid, :has_remaining_balance, :archived]
    belongs_to :taxpayer
    belongs_to :business

    validates :official_receipt_number, presence: true, uniqueness: true

    before_save :set_status_to_paid
    before_save :set_amount_paid

  def total
    subtotal - exemption + surcharge
  end

  def subtotal
   fees + taxes
  end

def fees
 mayors_permit_fee + police_clearance_fee + sanitary_inspection_fee + health_clearance_fee
end

def taxes
  return tax_on_capital if self.business.gross_sales.blank?
  return tax_on_gross_sales if self.business.gross_sales.present?
  return tax_on_cooperatives if self.business.cooperative?
end

  def exemption
    if self.business.cooperative?
      self.tax_on_gross_sales
    else
     0
    end
  end

  def surcharge
    if registration_date_lapsed? && self.business.delinquent?
      mayors_permit_fee * 0.25
   else
      0
    end
  end

  def mayors_permit_fee
    self.business.mayors_permit_fee_amount
  end

  def tax_on_capital
    self.business.capital_tax
  end

  def tax_on_gross_sales
    self.business.gross_sales_taxes_amount
  end
   def police_clearance_fee
        50
      end

      def sanitary_inspection_fee
        100
      end

      def health_clearance_fee
        100
      end

  private
      def self.uncollected_amount
        Business.delinquent.count * 1000
      end

  def tax_on_cooperatives
    0
  end
  def set_status_to_paid
    self.status=:paid
  end
  def set_amount_paid
    self.amount=total
  end
  def self.revenue_for_current_year
    self.sum(:amount)
  end

  def self.archive_all_payments
    self.paid.update_all(status: :archived)
  end
  def registration_date_lapsed?
    self.business.updated_at > Time.zone.now.beginning_of_year + 20.days
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
def index
   if params[:query].present?
      @payments = Payment.text_search(params[:query]).page(params[:page]).per_page(30)
    else
  @payments = Payment.order('created_at DESC').page(params[:page]).per_page(30)
end
end
def new
  unless current_business.registered?
  @payment = current_business.payments.build
  authorize @payment
end
end

def create
  @payment =current_business.payments.build(payment_params)
  authorize @payment
      @payment.collecting_officer= current_user.full_name
  if @payment.save
    @payment.business.update_payment_status

    redirect_to business_path(id: @payment.business_id), notice: 'Payment successfully made.'
  else
    render :new
  end
end

private
    def current_business
      @business=Business.find(params[:business_id])
    end

    def payment_params
      params.require(:payment).permit(:amount, :official_receipt_number)
    end
end

app/views/payments/_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
<div class="panel panel-default">
   <div class="panel-body">
<div class="col-md-5">
<h3 class="text-center help-block"><strong><%=@business.business_name.upcase %></strong></h3>
<hr/>
<p><strong>Industry: </strong> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<span><%=@business.industry_type.titleize %></span></p>
<hr>
<p><strong>Type of Business: </strong> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<%=@business.business_type.titleize %></span></p>
<hr>
<p><strong>Asset Size: </strong> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<%=number_to_currency @business.asset_size %></span></p>
<hr>
<br />

</div>
<div class="col-md-1">
<vr>
</div>
<div class='col-md-6'>

      <h4 class="text-center">Payment Breakdown </h4>
      <hr>
      <p class="text-center"><strong>Local Taxes</strong> </p>
      <hr />
 <% if @business.gross_sales.blank? %>
      <p>Business Tax<span class="pull-right"><%=number_to_currency(@business.capital_tax, unit: ' P ') %> </span></p>
      <% end %>
   <% unless @business.gross_sales.blank? %>
         <p>Gross Sales Tax<span class="pull-right"><%=number_to_currency(@business.gross_sales_taxes_amount, unit: 'P ') %> </span></p>
  <% end %>

    <br />
      <p class="text-center"><strong>Regulatory Fees and Charges</strong></p>
        <hr>
            <p>Mayors Permit Fee: <span class="pull-right"><%=number_to_currency(@business.mayors_permit_fee_amount, unit: ' P ') %></span></p>
            <p>Police Clearance Fee: <span class="pull-right"><%=number_to_currency(@payment.police_clearance_fee, unit: ' P ') %></span></p>
            <p>Sanitary Inspection Fee: <span class="pull-right"><%=number_to_currency(@payment.sanitary_inspection_fee, unit: ' P ') %></span></p>
            <p>Health Certificate Fee: <span class="pull-right"><%=number_to_currency(@payment.health_clearance_fee, unit: ' P ') %></span></p>
      <hr>
      <br />
      <p>Subtotal: <span class="pull-right"><%=number_to_currency(@payment.subtotal, unit: ' P ') %></span></p>
      <p>Exemptions: <span class="pull-right text-success"> - <%=@payment.exemption %></span></p>
      <p>Surcharges: <span class="pull-right text-danger"><%=@payment.surcharge %></span></p>
      <hr>
      <p>AMOUNT TO PAY <span class="pull-right text-info"><strong><%=number_to_currency(@payment.total, unit: ' P ') %></strong></span></p>
      <hr>
      <%=simple_form_for [@business, @payment] do |f| %>
        <%=f.input :official_receipt_number, input_html: {class: "input-lg"}, autofocus: true %>
        <div class="modal-footer">
          <%=f.submit 'Register Payment ', class: 'btn btn-primary'%>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/payments/index.html.erb
<%provide(:title, "Payments") %>
<div class="row">
<% if @payments.count.zero? %>
  <p class="alert alert-info">No Payments have been registered yet.</p>
<% else %>
  <div class="col-md-10 col-md-offset-1">
         <div class="box box-success">
                <div class="box-header with-border">
                <h3 class="box-title">All Payments</h3>
                  <div class="box-tools pull-right">

                    <%=form_tag payments_path, method: :get do %>
      <div class="input-group">
        <%=text_field_tag :query, params[:query], class: 'form-control', placeholder: 'Search...' %>
        <span class="input-group-btn">
          <%= button_tag(type: 'submit', class: "btn btn-flat") do %>
            <i class="fa fa-search"></i>
            <% end %>
               </span>
      </div>
      <% end %>
      </div>

                  </div>
      <div class="box-body">
        <div class="table-responsive">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th> Taxpayer</th>
                <th>Date of Payment</th>
                <th>Amount</th>
                <th>O.R. Number</th>
                <th>Collecting Officer</th>
              </tr>
            </thead>
            <tbody>
              <% @payments.each do |payment| %>
                <tr>
                  <td><%=payment.business.try(:taxpayer_name)%></td>
                  <td><%=payment.created_at.strftime('%B %d %Y')%></td>
                  <td class="pull-right"><%=number_to_currency(payment.amount, unit: ' P ' )%></td>
                  <td><%=payment.official_receipt_number %></td>
                  <td><%=payment.collecting_officer%></td>
                </tr>
              <%end%>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>