config/routes.rb
Rails.application.routes.draw do
    root 'pages#dashboard'
    get 'dashboard' => 'pages#dashboard'
    devise_for :users, :controllers => { :registrations => "users" }
    devise_for :taxpayers, :controllers => { :registrations => "taxpayers"}

    resources :users, except: [:destroy]

    resources :taxpayers do
      match :delinquent, via: [:get], on: :collection
       match :with_pending_payments, via: [:get], on: :collection
      resources :businesses
      resources :cedulas
    end
    resources :businesses, except: [:destroy] do
      match :renew, via: [:get], on: :member
      match :registered, via: [:get], on: :collection
      match :delinquent, via: [:get], on: :collection
      match :payment_pending, via: [:get], on: :collection
      match :new_business, via: [:get], on: :collection
      match :owned_by_women, via: [:get], on: :collection
      match :expire, via: [:get, :post], on: :member
      match :retire, via: [:get, :post], on: :member
      match :revoke, via: [:get, :post], on: :member
      match :revoked, via: :get, on: :collection
      resources :payments, only: [:new, :create]
      resources :line_of_businesses
    end
          resources :payments,  only: [:index]
          resources :line_of_businesses

      get 'reports' => 'reports#index', as: 'reports'
      get 'quarterly_reports' => 'reports#quarterly', as: 'quarterly_reports'
      get 'delinquents_ahin' => 'businesses#delinquents_ahin'
      get 'delinquents_apapid' => 'businesses#delinquents_apapid'
      get 'delinquents_binablayan' => 'businesses#delinquents_binablayan'
      get 'delinquents_danggo' => 'businesses#delinquents_danggo'
      get 'delinquents_eheb' => 'businesses#delinquents_eheb'
      get 'delinquents_gumhang' => 'businesses#delinquents_gumhang'
      get 'delinquents_impugong' => 'businesses#delinquents_impugong'
      get 'delinquents_luhong' => 'businesses#delinquents_luhong'
      get 'delinquents_poblacion' => 'businesses#delinquents_poblacion'
      get 'delinquents_tukucan' => 'businesses#delinquents_tukucan'
      get 'delinquents_tulludan' => 'businesses#delinquents_tulludan'
      get 'delinquents_wangwang' => 'businesses#delinquents_wangwang'

      get 'registered_ahin' => 'businesses#registered_ahin'
      get 'registered_apapid' => 'businesses#registered_apapid'
      get 'registered_binablayan' => 'businesses#registered_binablayan'
      get 'registered_danggo' => 'businesses#registered_danggo'
      get 'registered_eheb' => 'businesses#registered_eheb'
      get 'registered_gumhang' => 'businesses#registered_gumhang'
      get 'registered_impugong' => 'businesses#registered_impugong'
      get 'registered_luhong' => 'businesses#registered_luhong'
      get 'registered_poblacion' => 'businesses#registered_poblacion'
      get 'registered_tukucan' => 'businesses#registered_tukucan'
      get 'registered_tulludan' => 'businesses#registered_tulludan'
      get 'registered_wangwang' => 'businesses#registered_wangwang'

      get 'dole_report' => 'businesses#dole_report'
      get 'sss_report' => 'businesses#sss_report'
      get 'registered_businesses_report' => 'businesses#registered_businesses_report'
      get 'new_businesses_report' => 'businesses#new_businesses_report'
      get 'unrenewed_businesses_report' => 'businesses#unrenewed_businesses_report'
      get 'bir_report' => 'businesses#bir_report'
  end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end

  def quarterly
   # load_count_of_new_businesses
   # load_count_of_renewed_businesses
   # load_count_of_closed_businesses
   #  @count_of_renewed_businesses = Business.renewed.count
   #  @count_of_closed_businesses = Business.revoked.count
   #  @percentage_of_new_businesses_owned_by_women
   #  @percentage_of_renewed_businesses_owned_by_women
   #  @percentage_of_closed_businesses_owned_by_women
  end

  private
      def load_count_of_new_businesses
      end
end

app/views/reports/index.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-danger">
      <div class="panel-heading">Unrenewed Businesses Per Barangay</div>

    <ul class="list-group">
      <li class="list-group-item"><%=link_to 'Poblacion', delinquents_poblacion_path(format: :pdf), class: 'text-danger' %> <span class="badge pull-right bg-red"> <%=Business.delinquent.where(address_barangay: 'Poblacion').count %></span></li>


       <li class="list-group-item"><%=link_to 'Impugong', delinquents_impugong_path(format: :pdf), class: 'text-danger'  %> <span class="badge pull-right bg-red"> <%=Business.delinquent.where(address_barangay: 'Impugong').count %></span></p></li>

       <li class="list-group-item"><%=link_to 'Ahin', delinquents_ahin_path(format: :pdf), class: 'text-danger'  %> <span class="badge pull-right bg-red"> <%=Business.delinquent.where(address_barangay: 'Ahin').count %></span></li>

      <li class="list-group-item"><%=link_to 'Ap-apid', delinquents_apapid_path(format: :pdf), class: 'text-danger'  %> <span class="badge pull-right bg-red"> <%=Business.delinquent.where(address_barangay: 'Ap-apid').count %></span></li>

       <li class="list-group-item"><%=link_to 'Binablayan', delinquents_binablayan_path(format: :pdf), class: 'text-danger'  %> <span class="badge pull-right bg-red"> <%=Business.delinquent.where(address_barangay: 'Binablayan').count %></span></li>

       <li class="list-group-item"><%=link_to 'Wangwang', delinquents_wangwang_path(format: :pdf), class: 'text-danger'  %> <span class="badge pull-right bg-red"> <%=Business.delinquent.where(address_barangay: 'Wangwang').count %></span></li>

       <li class="list-group-item"><%=link_to 'Gumhang', delinquents_gumhang_path(format: :pdf), class: 'text-danger'  %> <span class="badge pull-right bg-red"> <%=Business.delinquent.where(address_barangay: 'Gumhang').count %></span></li>

       <li class="list-group-item"><%=link_to 'Danggo', delinquents_danggo_path(format: :pdf), class: 'text-danger'  %> <span class="badge pull-right bg-red"> <%=Business.delinquent.where(address_barangay: 'Danggo').count %></span></li>

       <li class="list-group-item"><%=link_to 'Luhong', delinquents_luhong_path(format: :pdf), class: 'text-danger'  %> <span class="badge pull-right bg-red"> <%=Business.delinquent.where(address_barangay: 'Luhong').count %></span></li>

       <li class="list-group-item"><%=link_to 'Tukucan', delinquents_tukucan_path(format: :pdf), class: 'text-danger'  %> <span class="badge pull-right bg-red"> <%=Business.delinquent.where(address_barangay: 'Tukucan').count %></span></li>

      <li class="list-group-item"><%=link_to 'Tulludan', delinquents_tulludan_path(format: :pdf), class: 'text-danger'  %> <span class="badge pull-right bg-red"> <%=Business.delinquent.where(address_barangay: 'Tulludan').count %></span></li>
       <li class="list-group-item"><%=link_to 'Eheb', delinquents_eheb_path(format: :pdf), class: 'text-danger'  %> <span class="badge pull-right bg-red"> <%=Business.delinquent.where(address_barangay: 'Eheb').count %></span></li>
    </ul>
  </div>
  </div>

  <div class="row">
  <div class="col-md-4">
    <div class="panel panel-success">
      <div class="panel-heading">Registered Businesses Per Barangay</div>

    <ul class="list-group">
      <li class="list-group-item"><%=link_to 'Poblacion', registered_poblacion_path(format: :pdf), class: 'text-success' %> <span class="badge pull-right bg-green"> <%=Business.registered.where(address_barangay: 'Poblacion').count %></span></li>


       <li class="list-group-item"><%=link_to 'Impugong', registered_impugong_path(format: :pdf), class: 'text-success'  %> <span class="badge pull-right bg-green"> <%=Business.registered.where(address_barangay: 'Impugong').count %></span></p></li>

       <li class="list-group-item"><%=link_to 'Ahin', registered_ahin_path(format: :pdf), class: 'text-success'  %> <span class="badge pull-right bg-green"> <%=Business.registered.where(address_barangay: 'Ahin').count %></span></li>

      <li class="list-group-item"><%=link_to 'Ap-apid', registered_apapid_path(format: :pdf), class: 'text-success'  %> <span class="badge pull-right bg-green"> <%=Business.registered.where(address_barangay: 'Ap-apid').count %></span></li>

       <li class="list-group-item"><%=link_to 'Binablayan', registered_binablayan_path(format: :pdf), class: 'text-success'  %> <span class="badge pull-right bg-green"> <%=Business.registered.where(address_barangay: 'Binablayan').count %></span></li>

       <li class="list-group-item"><%=link_to 'Wangwang', registered_wangwang_path(format: :pdf), class: 'text-success'  %> <span class="badge pull-right bg-green"> <%=Business.registered.where(address_barangay: 'Wangwang').count %></span></li>

       <li class="list-group-item"><%=link_to 'Gumhang', registered_gumhang_path(format: :pdf), class: 'text-success'  %> <span class="badge pull-right bg-green"> <%=Business.registered.where(address_barangay: 'Gumhang').count %></span></li>

       <li class="list-group-item"><%=link_to 'Danggo', registered_danggo_path(format: :pdf), class: 'text-success'  %> <span class="badge pull-right bg-green"> <%=Business.registered.where(address_barangay: 'Danggo').count %></span></li>

       <li class="list-group-item"><%=link_to 'Luhong', registered_luhong_path(format: :pdf), class: 'text-success'  %> <span class="badge pull-right bg-green"> <%=Business.registered.where(address_barangay: 'Luhong').count %></span></li>

       <li class="list-group-item"><%=link_to 'Tukucan', registered_tukucan_path(format: :pdf), class: 'text-success'  %> <span class="badge pull-right bg-green"> <%=Business.registered.where(address_barangay: 'Tukucan').count %></span></li>

      <li class="list-group-item"><%=link_to 'Tulludan', registered_tulludan_path(format: :pdf), class: 'text-success'  %> <span class="badge pull-right bg-green"> <%=Business.registered.where(address_barangay: 'Tulludan').count %></span></li>
       <li class="list-group-item"><%=link_to 'Eheb', registered_eheb_path(format: :pdf), class: 'text-success'  %> <span class="badge pull-right bg-green"> <%=Business.registered.where(address_barangay: 'Eheb').count %></span></li>
    </ul>
  </div>
  </div>

  <div class="col-md-4">
    <a href="#" class="list-group-item active">
      Reports
    </a>
    <ul class="list-group">
      <li class="list-group-item">  <%=link_to 'DOLE Report', dole_report_path(format: :pdf) %></li>
       <li class="list-group-item">  <%=link_to 'SSS Report', sss_report_path(format: :pdf) %></li>
      <li class="list-group-item">  <%=link_to 'BIR Report',bir_report_path(format: :pdf) %></li>
        <li class="list-group-item">  <%=link_to 'Registered  Businesses Report', registered_businesses_report_path(format: :pdf) %></li>
         <li class="list-group-item">  <%=link_to 'New Businesses Report', new_businesses_report_path(format: :pdf) %></li>
         <li class="list-group-item">  <%=link_to 'Unrenewed  Businesses Report', unrenewed_businesses_report_path(format: :pdf) %></li>
    </ul>
  </div>
</div>

app/views/reports/quarterly.html.erb
<h1>Owned By Women</h1>
<div class="col-sm-2">
<div class="panel panel-default">
<h1 class="centered"><%=Business.new_business.on_first_quarter.count %></h1>
<h3>New Businesses</h3>
</div>
</div>
<div class="col-sm-2">
<div class="panel panel-default">
<h3><%=Business.registered.on_first_quarter.count %></h3>
<h3>Renewed Businesses</h3>
</div>
</div>
<div class="col-sm-2">
<div class="panel">
<h3><%=Business.revoked.on_first_quarter.count %></h3>
<h3>Closed Businesses</h3>
</div>
</div>

<div class="col-sm-2">
<div class="panel">
<h3><%=Business.new_business.owned_by_women.count %></h3>
<h3>New Business Owned By Women</h3>
</div>
</div>